#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    companyName:
      type: string
      example: "TransNational"
      required: true
    availableSeats:
      type: number
      example: 20
      required: true
    departureDateTime:
      type: string
      example: "2019-04-30T16:41:41"
      required: true
    travelRoute:
      type: object
      properties:
        destinationLocation:
          type: object
          properties:
            locationCode:
              type: string
              example: "BEN-SG"
              required: true
            locationDesc:
              type: string
              example: "Beauna Vista Singapore"
              required: true
        originLocation:
          type: object
          properties:
            locationCode:
              type: string
              example: "BEN-SG"
              required: true
            locationDesc:
              type: string
              example: "Beauna Vista Singapore"
              required: true